"""`clip_latent_global_means` must track a global mean, not a tile mean.

The option shifts the post-encoder latent so its per-channel spatial mean falls
inside an envelope observed during training. Both halves of that -- the mean
and the envelope -- have to be global, or each spatial co-rank learns a
different envelope from a different statistic and applies a different shift at
eval time, and the model's behaviour then depends on how the run was
decomposed.

Baselines must be generated by a single-rank ``python -m pytest`` run and
committed; regenerating them under torchrun compares a decomposition against
itself.
"""

import pathlib

import pytest
import torch

import fme
from fme.core.distributed.distributed import Distributed
from fme.core.models.conditional_sfno.layers import Context
from fme.core.models.conditional_sfno.sfnonet import SFNONetConfig, get_lat_lon_sfnonet
from fme.core.testing.regression import validate_tensor_dict

IMG_SHAPE = (16, 32)
DATA_DIR = pathlib.Path(__file__).parent / "testdata"


def _build_net():
    torch.manual_seed(0)
    return get_lat_lon_sfnonet(
        params=SFNONetConfig(
            embed_dim=4,
            num_layers=1,
            clip_latent_global_means=True,
        ),
        in_chans=2,
        out_chans=2,
        img_shape=IMG_SHAPE,
    ).to(fme.get_device())


def _global_input(n_samples: int = 2) -> torch.Tensor:
    torch.manual_seed(1)
    # a spatially structured field, so tile means differ from the global mean
    lat = torch.linspace(-1.0, 1.0, IMG_SHAPE[0]).reshape(-1, 1)
    lon = torch.linspace(0.0, 6.0, IMG_SHAPE[1]).reshape(1, -1)
    base = torch.sin(lon) + 2.0 * lat
    field = base.expand(n_samples, 2, *IMG_SHAPE).clone()
    field += 0.1 * torch.randn_like(field)
    return field.to(fme.get_device())


def _context() -> Context:
    return Context(embedding_scalar=None, embedding_pos=None, labels=None, noise=None)


@pytest.mark.parallel
def test_latent_envelope_is_decomposition_invariant():
    dist = Distributed.get_instance()
    net = _build_net()
    global_input = _global_input()
    local_input = global_input[(..., *dist.get_local_slices(IMG_SHAPE))].contiguous()

    net.train()
    net(local_input, _context())

    # The envelope is a global quantity, so it is identical on every rank and
    # must equal what a single-rank run recorded.
    validate_tensor_dict(
        {"gm_min": net._gm_min.cpu(), "gm_max": net._gm_max.cpu()},
        DATA_DIR / "latent_clip_envelope.pt",
        rtol=1e-5,
        atol=1e-6,
    )


@pytest.mark.parallel
def test_latent_clip_eval_output_is_decomposition_invariant():
    dist = Distributed.get_instance()
    net = _build_net()
    global_input = _global_input()
    local_input = global_input[(..., *dist.get_local_slices(IMG_SHAPE))].contiguous()

    net.train()
    net(local_input, _context())

    net.eval()
    # shift the input so its latent mean lands outside the training envelope,
    # making the clip actually fire rather than being a no-op
    with torch.no_grad():
        shifted = local_input + 5.0
        output = net(shifted, _context())

    gathered = dist.gather_spatial_tensor(output, IMG_SHAPE)
    validate_tensor_dict(
        {"output": gathered.cpu()},
        DATA_DIR / "latent_clip_eval_output.pt",
        rtol=1e-4,
        atol=1e-5,
    )
