"""Decomposition invariance of the noise-conditioned SFNO's random draws.

The property under test is the same for every decomposition: with a given
seed, the *assembled global* stochastic field must be the field a single-rank
run would have drawn. That is what makes a spatially-parallel run reproducible
and comparable against a serial one, and it is what a per-tile draw silently
breaks -- spatial co-ranks share a seed and an RNG history, so each tile of a
sample gets the same numbers and the global field repeats one pattern.

The baselines under ``testdata/`` must be generated by a single-rank
``python -m pytest`` run and committed; regenerating them under torchrun would
compare a decomposition against itself and prove nothing.
"""

import pathlib

import pytest
import torch

import fme
from fme.core.distributed.distributed import Distributed
from fme.core.rand import randn, spatial_randn
from fme.core.testing.regression import NestedTensorDict, validate_tensor_dict

IMG_SHAPE = (16, 32)
DATA_DIR = pathlib.Path(__file__).parent / "testdata"


def _local_slices(img_shape):
    return Distributed.get_instance().get_local_slices(img_shape)


def _local_img_shape() -> tuple[int, int]:
    """This rank's tile shape, via a real slice so it holds for every backend."""
    probe = torch.zeros(IMG_SHAPE)[(..., *_local_slices(IMG_SHAPE))]
    return (probe.shape[-2], probe.shape[-1])


def _assert_tiles_differ(gathered: torch.Tensor) -> None:
    """Fail if the tiles of the assembled field repeat each other.

    This is the specific signature a local-shape draw leaves, and it does not
    depend on any particular RNG implementation.
    """
    h_size, w_size = Distributed.get_instance().spatial_shape
    if h_size * w_size == 1:
        return  # one tile; nothing to repeat
    h_local, w_local = IMG_SHAPE[0] // h_size, IMG_SHAPE[1] // w_size
    first = gathered[..., :h_local, :w_local]
    for i in range(h_size):
        for j in range(w_size):
            if (i, j) == (0, 0):
                continue
            other = gathered[
                ...,
                i * h_local : (i + 1) * h_local,
                j * w_local : (j + 1) * w_local,
            ]
            assert not torch.allclose(first, other), (
                f"tile ({i}, {j}) repeats tile (0, 0): the field is tiled at "
                "the decomposition scale"
            )


@pytest.mark.parallel
def test_spatial_randn_is_a_slice_of_the_global_draw():
    """Each rank holds exactly its slice of the field one rank would draw."""
    leading = (2, 3)
    torch.manual_seed(0)
    expected_global = randn(torch.Size((*leading, *IMG_SHAPE)), device=fme.get_device())

    torch.manual_seed(0)
    local = spatial_randn(leading, IMG_SHAPE, device=fme.get_device())

    slices = _local_slices(IMG_SHAPE)
    torch.testing.assert_close(local, expected_global[(..., *slices)])


@pytest.mark.parallel
def test_spatial_randn_assembles_to_the_global_draw():
    dist = Distributed.get_instance()
    leading = (2, 3)
    torch.manual_seed(0)
    expected_global = randn(torch.Size((*leading, *IMG_SHAPE)), device=fme.get_device())

    torch.manual_seed(0)
    gathered = dist.gather_spatial_tensor(
        spatial_randn(leading, IMG_SHAPE, device=fme.get_device()), IMG_SHAPE
    )

    torch.testing.assert_close(gathered, expected_global)
    _assert_tiles_differ(gathered)


def _noise_conditioned_model(noise_type: str):
    from fme.ace.registry.stochastic_sfno import NoiseConditionedSFNOBuilder
    from fme.core.testing.dataset_info import get_dataset_info

    builder = NoiseConditionedSFNOBuilder(
        embed_dim=4,
        noise_embed_dim=3,
        num_layers=1,
        noise_type=noise_type,  # type: ignore[arg-type]
    )
    return builder.build(
        n_in_channels=2,
        n_out_channels=2,
        dataset_info=get_dataset_info(img_shape=IMG_SHAPE),
    ).to(fme.get_device())


@pytest.mark.parametrize("noise_type", ["gaussian", "isotropic"])
@pytest.mark.parallel
def test_conditioning_noise_is_decomposition_invariant(noise_type):
    """The noise the wrapped SFNO sees must assemble to the serial field.

    Captures the ``Context.noise`` handed to the inner module rather than
    re-deriving it, so this covers the model's own call site and the isotropic
    path's distributed inverse SHT as well as the gaussian draw.
    """
    dist = Distributed.get_instance()
    model = _noise_conditioned_model(noise_type)

    captured: dict[str, torch.Tensor] = {}
    inner = model.conditional_model

    def capture(x, context):
        captured["noise"] = context.noise
        return original_forward(x, context)

    original_forward = inner.forward
    inner.forward = capture  # type: ignore[method-assign]

    x = torch.zeros(1, 2, *_local_img_shape(), device=fme.get_device())

    torch.manual_seed(0)
    model(x)
    gathered = dist.gather_spatial_tensor(captured["noise"], IMG_SHAPE)

    assert gathered.shape[-2:] == IMG_SHAPE
    _assert_tiles_differ(gathered)
    result: NestedTensorDict = {"noise": gathered.cpu()}
    validate_tensor_dict(
        result,
        DATA_DIR / f"conditioning_noise_{noise_type}.pt",
        rtol=1e-5,
        atol=1e-6,
    )


@pytest.mark.xfail(
    strict=True,
    reason=(
        "Known defect, not introduced by spatial parallelism: every rank is "
        "seeded identically and draws the same shape, so data-parallel ranks "
        "produce identical conditioning noise for corresponding samples. The "
        "realizations in a global batch are therefore correlated in groups, "
        "and only batch_size/n_data_ranks of them are independent. Fixing it "
        "means keying the draw on the global sample index, which changes "
        "existing multi-rank training results and every committed baseline "
        "for this model, so it needs an owner's decision rather than a "
        "drive-by change. When it is fixed, drop this marker."
    ),
)
@pytest.mark.parallel
def test_data_parallel_ranks_draw_independent_noise():
    """Ranks holding different samples should draw different noise."""
    dist = Distributed.get_instance()
    n_dp = dist.total_data_parallel_ranks
    if n_dp == 1:
        pytest.skip("needs more than one data-parallel rank")
    spatial_size = dist.world_size // n_dp

    torch.manual_seed(2)
    local = spatial_randn((1, 2), IMG_SHAPE, device=fme.get_device())
    assembled = dist.gather_spatial_tensor(local, IMG_SHAPE).contiguous()
    per_rank = [torch.zeros_like(assembled) for _ in range(dist.world_size)]
    torch.distributed.all_gather(per_rank, assembled)

    # one representative rank per data group
    first = per_rank[0]
    for data_rank in range(1, n_dp):
        other = per_rank[data_rank * spatial_size]
        assert not torch.allclose(
            first, other
        ), f"data rank {data_rank} drew the same noise as data rank 0"
