"""Gradient parity between a decomposed run and a single-rank one.

This is the property that makes spatially-parallel training meaningful: after
a backward pass every rank must hold the gradient a single-rank run would have
computed on the same global batch. Spatial co-ranks each see one tile, so each
holds a partial sum; the reduction that turns those partials back into the
whole is the thing under test, and it is only correct while the parameters are
genuinely replicated across the spatial group.

Baselines must be generated by a single-rank ``python -m pytest`` run and
committed.
"""

import pathlib

import pytest
import torch

import fme
from fme.core.distributed.distributed import Distributed
from fme.core.distributed.parameter_placement import (
    SpatiallyShardedParameter,
    synchronize_replicated_parameters,
)
from fme.core.testing.regression import validate_tensor_dict

IMG_SHAPE = (16, 32)
N_SAMPLES = 2
DATA_DIR = pathlib.Path(__file__).parent / "testdata"


def _build_model():
    from fme.ace.registry.stochastic_sfno import NoiseConditionedSFNOBuilder
    from fme.core.testing.dataset_info import get_dataset_info

    torch.manual_seed(0)
    builder = NoiseConditionedSFNOBuilder(
        embed_dim=4,
        noise_embed_dim=3,
        num_layers=2,
    )
    return builder.build(
        n_in_channels=2,
        n_out_channels=2,
        dataset_info=get_dataset_info(img_shape=IMG_SHAPE),
    ).to(fme.get_device())


def _global_input() -> torch.Tensor:
    torch.manual_seed(1)
    return torch.randn(N_SAMPLES, 2, *IMG_SHAPE, device=fme.get_device())


def _backward(dist: Distributed) -> dict[str, torch.Tensor]:
    """One forward/backward on this rank's share, returning its gradients."""
    model = _build_model()
    wrapped = dist.wrap_module(model)

    global_input = _global_input()
    local = global_input[
        (..., *dist.get_local_slices(global_input.shape, data_parallel_dim=0))
    ].contiguous()

    torch.manual_seed(2)
    output = wrapped(local)
    # a spatially-reduced weighted mean, so the backward pass runs through the
    # same `spatial_reduce_sum` the real losses use
    weights = torch.ones(output.shape[-2:], device=output.device)
    dist.weighted_mean(output**2, weights, dim=(-2, -1)).mean().backward()

    grads = {
        name.removeprefix("module."): param.grad.detach()
        for name, param in wrapped.named_parameters()
        if param.grad is not None
    }
    assert grads, "expected gradients on the wrapped model"
    return grads


@pytest.mark.parallel
def test_gradients_match_single_rank():
    """Every gradient against the baseline a single-rank run produced.

    Skipped when the batch is also split across data-parallel ranks: those
    ranks draw *identical* conditioning noise (see
    ``test_noise.test_data_parallel_ranks_draw_independent_noise``), so a
    data-parallel run is not evaluating the same function as the serial one
    and the comparison would be measuring that defect rather than this
    reduction. The spatial axis, which is what changes here, is still covered
    at every h/w layout, and
    ``test_gradients_agree_across_spatial_co_ranks`` covers the hybrid.
    """
    dist = Distributed.get_instance()
    if dist.total_data_parallel_ranks > 1:
        pytest.skip("data-parallel ranks draw identical noise; see docstring")
    grads = {k: v.cpu() for k, v in _backward(dist).items()}
    validate_tensor_dict(grads, DATA_DIR / "sfno_gradients.pt", rtol=2e-4, atol=2e-6)


@pytest.mark.parallel
def test_gradients_agree_across_spatial_co_ranks():
    """Spatial co-ranks must end a backward pass holding the same gradient.

    They hold the same replicated parameters and are about to take the same
    optimizer step, so any disagreement means the ranks diverge into different
    models. Unlike the baseline comparison this holds at any layout, including
    data x spatial, because it compares within a data group rather than
    against a serial run.
    """
    dist = Distributed.get_instance()
    if not dist.has_spatial_parallelism:
        pytest.skip("no spatial co-ranks to compare against")
    spatial_group = dist._distributed._spatial_group

    for name, grad in _backward(dist).items():
        lo, hi = grad.clone(), grad.clone()
        torch.distributed.all_reduce(
            lo, op=torch.distributed.ReduceOp.MIN, group=spatial_group
        )
        torch.distributed.all_reduce(
            hi, op=torch.distributed.ReduceOp.MAX, group=spatial_group
        )
        torch.testing.assert_close(
            lo, hi, rtol=0, atol=0, msg=f"{name} differs across spatial co-ranks"
        )


@pytest.mark.parallel
def test_identically_seeded_model_needs_no_correction():
    """An identically-seeded build already agrees, so nothing is overwritten."""
    dist = Distributed.get_instance()
    if not dist.has_spatial_parallelism:
        pytest.skip("no spatial group to compare across")
    model = _build_model()
    assert (
        synchronize_replicated_parameters(model, dist._distributed._spatial_group) == []
    )


@pytest.mark.parallel
def test_sharded_parameter_is_rejected():
    """A parameter sized from the local extent must be refused, not summed.

    This is the failure mode that makes localizing the spectral weights unsafe
    on its own: the shapes still line up, so the spatial sum runs and quietly
    updates each shard with the sum of gradients belonging to different
    spectral modes.
    """
    dist = Distributed.get_instance()
    h_size, _ = dist.spatial_shape
    if h_size == 1:
        pytest.skip("needs an h decomposition to give ranks different sizes")

    module = torch.nn.Module()
    module.weight = torch.nn.Parameter(
        torch.zeros(8 // h_size + dist.rank % 2, device=fme.get_device())
    )
    with pytest.raises(SpatiallyShardedParameter, match="spatially sharded"):
        synchronize_replicated_parameters(module, dist._distributed._spatial_group)


@pytest.mark.parallel
def test_diverged_initialization_is_repaired():
    """Replicated parameters that start out different are pulled into line.

    Same shape on every rank, so nothing downstream would notice; the ranks
    would apply the same summed gradient to different weights forever and no
    rank would hold the model anyone thinks was trained. DDP performs the
    equivalent broadcast over the data group and leaves the spatial group to
    whoever remembered to seed it.
    """
    dist = Distributed.get_instance()
    if not dist.has_spatial_parallelism:
        pytest.skip("no spatial group to compare across")
    spatial_group = dist._distributed._spatial_group

    module = torch.nn.Module()
    module.weight = torch.nn.Parameter(
        torch.full((4,), float(dist.rank), device=fme.get_device())
    )
    corrected = synchronize_replicated_parameters(module, spatial_group)

    spatial_root_value = float(dist.rank - torch.distributed.get_rank(spatial_group))
    torch.testing.assert_close(
        module.weight.detach(),
        torch.full((4,), spatial_root_value, device=fme.get_device()),
    )
    if torch.distributed.get_world_size(spatial_group) > 1:
        assert corrected == ["weight"]
